### ISSUE TITLE
ETIMEDOUT 63.247.71.18 app crash

### ISSUE THREAD

**Issue by jumoog** [kacperzuk/nastyhosts#7]
**63.247.71.18:80 = bgp.he.net**

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 63.247.71.18:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
```

**Comment by kacperzuk** [comment]
Hi,

I'm not sure why NastyHosts is trying to connect to bgp.he.net or this IP address. bgp.he.net has IP addreess 72.52.94.234, and according to http://viewdns.info/reverseip/?host=63.247.71.18&t=1 63.247.71.18 is more likely a shared hosting. Why do you think it's bgp.he.net?

Can you tell me which commit are you using and what's in your config.json file?

**Comment by jumoog** [comment]
default config.json and im using master branch 

oh i googled 63.247.71.18  and thought its bgp.he.net

// Edit

how i can debug this?

**Comment by kacperzuk** [comment]
Ok, I've found where the connection is made. It's a connection to software77.net from which an IP to country mapping is downloaded.

For a temporary workaround you can remove "countries" filter from config.json. I'll add a proper fix later.
